### PR TITLE
[#1370] Fix cleanup with 'dev_permissions' feature flag

### LINKED ISSUE #1370: Resources cannot always be cleaned up with 'dev_permissions' feature flag
Before posting the bug, take a look at the
[FAQ](https://github.com/eclipse-iceoryx/iceoryx2/blob/main/FAQ.md)
for a possible solution.

## Required information

**Operating system:**

* Linux, 2.19
* other OSes are probably also affected

**Rust version:**

any

**Cargo version:**

any

**iceoryx2 version:**

Probably present since the introduction of the `dev_permissions` feature flag

**Detailed log output:**

> 1 [E] SharedMemory { name: FileName { value: StaticString<255> { len: 80, data: "iox2_0354a209029e7d094a819e2d4030ea331e6caaf0_95202013074162211780128991149.data" } }, has_ownership: AtomicBool(true), memory_mapping: MemoryMapping { file_descriptor: Some(FileDescriptor { value: 6, is_owned: true }), file_path: None, base_address: 0x7f12e807c000, size: 2470, offset: 0 }, memory_lock: None, mapping_offset: 0 }
| Failed to cleanup shared memory since the permissions could not be adjusted (InsufficientPermissions).
> 2 [E] "Service::remove_node_from_service(NodeId(UniqueSystemId { value: 15948803921282728757882316717, pid: 59309, creation_time: Time { clock_type: Monotonic, seconds: 14295, nanoseconds: 864586393 } }), ServiceId(RestrictedFileName { value: StaticString<64> { len: 40, data: \"4eacadf2695a3f4b2eb95485759246ce1a2aa906\" } }))"
| Unable to remove static config of unused service (InternalError).
> 3 [E] "Service::remove_node_from_service(NodeId(UniqueSystemId { value: 15948803921282728757882316717, pid: 59309, creation_time: Time { clock_type: Monotonic, seconds: 14295, nanoseconds: 864586393 } }), ServiceId(RestrictedFileName { value: StaticString<64> { len: 40, data: \"4eacadf2695a3f4b2eb95485759246ce1a2aa906\" } }))"
| Unable to remove static config of unused service (InternalError).
Error: PublishSubscribeOpenError(IsMarkedForDestruction)

**Observed result or behaviour:**

When the `dev_permissions` flag is used, any app is entitles to perform the cleanup. But when an app terminates abnormally and the app to cleanup runs under a different user than the one that terminated, the permission cannot be changed and the error with the log from above occurs.

**Expected result or behaviour:**

The cleanup works with the `dev_permissions` feature flag even it the resources to be cleaned up were created by an application running under a different user.

**Conditions where it occurred / Performed steps:**

Terminal 1:
```
cargo build --example publish_subscribe_publisher --features iceoryx2/dev_permissions
sudo -u testuser -- target/debug/examples/publish_subscribe_publisher
```

Terminal 2:
```
sudo killall -9 publish_subscribe_publisher
target/debug/examples/publish_subscribe_publisher
```

**Underlying issue:**

Changing the file permissions to have write access before deleting the file is required (at least) on Windows. At some locations, the failure to change the file permissions generates only a warning instead of an error. It needs to be checked whether the same approach also works for the `set_permission` call in:

* iceoryx2-cal/src/static_storage/file.rs
* iceoryx2-bb/posix/src/shared_memory.rs

If not, the change of the permissions needs to be abstracted away is the PAL layer and performed only on the platforms that require this.

### PR DESCRIPTION
**Pull request by elBoberido**
## Notes for Reviewer

This PR addresses the issue where resources cannot always be cleaned up, even with the `dev_permissions` flag. The problem occurs when attempting to change file permissions before deletion, as a process running under a different user cannot modify permissions, even if they are already set to 777.

Instead of raising an error, the PR now prints a warning if changing file permissions fails. In such cases, the subsequent deletion attempt will fail on OSes that require files to be writable before deletion, e.g. on Windows.

This behavior, printing a warning instead of an error when setting permissions before deletion, is already used elsewhere in the codebase, so this change does not introduce a regression on Windows.

## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * Keep in mind to use the same email that was used to sign the [Eclipse Contributor Agreement][eca]
* [~] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [x] Assign PR to reviewer
* [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## PR Reviewer Reminders

* Commits are properly organized and messages are according to the guideline
* Unit tests have been written for new behavior
* Public API is documented
* PR title describes the changes

## References

Closes #1370

### CODE REVIEW

File: iceoryx2-bb/posix/src/shared_memory.rs [hunk 1]
```diff
@@ -420,17 +420,17 @@ pub struct SharedMemory {
...
-                        trace!(from self, "delete");
-                    }
-                    Err(_) => {
-                        error!(from self, "Failed to cleanup shared memory.");
-                    }
-                },
-                Err(e) => {
-                    error!(from self, "Failed to cleanup shared memory since the permissions could not be adjusted ({:?}).", e);
+            if let Err(e) = self.set_permission(Permission::OWNER_ALL) {
+                warn!(from self,
```
Comment (elfenpiff) [inline iceoryx2-bb/posix/src/shared_memory.rs]: Can you please print this warning only when `Self::shm_unlink` has failed. If `shm_unlink` succeeds this warning is meaningless.

File: iceoryx2-cal/src/static_storage/file.rs [hunk 2]
```diff
@@ -216,9 +216,10 @@ impl crate::named_concept::NamedConceptMgmt for Storage {
             }
         };
 
-        fail!(from origin, when file.set_permission(Permission::OWNER_ALL),
-                with NamedConceptRemoveError::InternalError,
-                "{} since the permissions could not be adjusted.", msg);
+        if let Err(e) = file.set_permission(Permission::ALL) {
+            warn!(from origin,
```
Comment (elfenpiff) [inline iceoryx2-cal/src/static_storage/file.rs]: Same thing here, please print this warning only when `File::remove` has failed to provide more context on why it have failed. Otherwise, it is somehow meaningless.

File: iceoryx2-bb/posix/src/shared_memory.rs (hunk 1 above)
Comment (elBoberido) [reply iceoryx2-bb/posix/src/shared_memory.rs]: This is analogues to other places where the warning is also printed independently of follow up error. Shall it be changed also at those locations?

**Comment by elBoberido** [comment]
@elfenpiff there is still the issue that the sticky bit is set on `/dev/shm`, which means that only the owner can remove the shared memory. So, I guess with `dev_permissions`, one needs to remove the sticky bit from `/dev/shm`, right? This might not be desirable. An alternative would be to have a separate in-memory filesystem for iceoryx2, separate from `/dev/shm` like described in #1223

**Comment by elfenpiff** [comment]
@elBoberido yes you are right. We could achieve this by using the file variant of the dynamic storage, shared memory, resizeable shared memory and zero copy connection in the recommended.rs files when the dev_permissions flag is set.

But that would mean that the users must ensure that `/tmp/` is an in-memory fs.
