### PR TITLE
[#1327] Use target switches for POSIX usage instead of feature

### LINKED ISSUE #1327: Remove posix feature from crates
## Brief Description

The `posix` feature defined in some crates is used to switch between implementations of structs that utilize `std` and equivalents that work directly with the POSIX platform abstraction.

This approach does not work so well when building tests for `no_std`. Furthermore, the additional feature switch adds some configuration complexity.

### PR DESCRIPTION
**Pull request by orecham**
## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Relevant issues are linked in the [References](#references) section
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * Keep in mind to use the same email that was used to sign the [Eclipse Contributor Agreement][eca]
* [ ] ~~Tests follow the [best practice for testing][testing]~~
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [ ] Assign PR to reviewer
* [ ] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## PR Reviewer Reminders

* Commits are properly organized and messages are according to the guideline
* Unit tests have been written for new behavior
* Public API is documented
* PR title describes the changes

## References

Closes #1327

### CODE REVIEW

File: iceoryx2-bb/loggers/src/console.rs [hunk 1]
```diff
@@ -47,7 +47,7 @@ fn duration_since_epoch() -> core::time::Duration {
             .duration_since(std::time::UNIX_EPOCH)
             .unwrap()
     }
-    #[cfg(feature = "posix")]
+    #[cfg(all(not(feature = "std"), any(target_os = "linux", target_os = "nto",)))]
```
Comment (orecham) [inline iceoryx2-bb/loggers/src/console.rs:50]: Doing this switch in this crate is a temporary solution ... An abstraction that takes care of switching between std/posix/bare metal would be better IMO, but we need another layer between the posix abstraction and the upper layers to do this nicely. Left for another time.

File: iceoryx2-pal/print/src/writer.rs [hunk 2]
```diff
@@ -120,35 +120,47 @@ impl Write for Stderr {
...
     fn is_terminal(&self) -> bool {
         true
     }
 }
 
-#[cfg(not(any(feature = "std", feature = "posix")))]
+#[cfg(all(
+    not(feature = "std"),
+    not(any(target_os = "linux", target_os = "nto",))
+))]
```
Comment (elBoberido) [inline iceoryx2-pal/print/src/writer.rs:133]: Food for thought. Could this be handled in a similar fashion to `platform_override`, which is set in the `build.rs` and then you could just use `not(posix)` instead of `not(any(target_os = "linux", target_os = "nto",))`? This could make it potentially also configurable for ouf-of-tree platforms

Comment (orecham) [reply iceoryx2-pal/print/src/writer.rs:133]: Worth considering. It would also keep the list of targets with POSIX in one place. I wonder if we would then need to add a build.rs to every crate though.

Comment (elBoberido) [reply iceoryx2-pal/print/src/writer.rs:133]: Yes, every crate which would use this `cfg` would need a `build.rs`. Unfortunately, it is not possible to use any constant expression in a `cfg` attribute.
