### PR TITLE
[#808] runtime fixed-size flatmaps

### LINKED ISSUE #808: FlatMap
## Brief feature description

It would be cool if iceoryx2 provides a `FlatMap` which could reuse the `iceoryx2_bb_container::slotmap::SlotMap` underneath but allows to insert passed key-value-pairs directly and adds related logic like checking if a key already exists before inserting a key-value-pair. Like the `SlotMap`, the `FlatMap` shall be available in 3 variants: a shared-memory-compatible `FixedSizeFlatMap` + `RelocatableFlatMap`, and a `FlatMap` that uses the heap.

### PR DESCRIPTION
**Pull request by FerdinandSpitzschnueffler**
## Notes for Reviewer

This PR implements the runtime fized-size flatmaps (`RelocatableFlatMap` and `FlatMap`). Additionally, the last commit makes the documentation of all runtime fixed-size containers visible by mainly removing the `details` module. Please check the documentation if these changes are suitable; if not, they can be easily reverted.

## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * [x] Commit author matches [Eclipse Contributor Agreement][eca](and ECA is signed)
* [x] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [x] Assign PR to reviewer
* [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

* [x] Commits are properly organized and messages are according to the guideline
* [x] Unit tests have been written for new behavior
* [x] Public API is documented
* [x] PR title describes the changes

## Post-review Checklist for the PR Author

* [x] All open points are addressed and tracked via issues

## References

Closes #808

### CODE REVIEW

File: iceoryx2-bb/container/src/queue.rs [hunk 1]
```diff
@@ -117,337 +118,332 @@ use iceoryx2_pal_concurrency_sync::iox_atomic::IoxAtomicBool;
...
 /// Queue with run-time fixed size capacity. In contrast to its counterpart the
 /// [`RelocatableQueue`] it is movable but is not shared memory compatible.
-pub type Queue<T> = details::MetaQueue<T, GenericOwningPointer>;
+pub type Queue<T> = MetaQueue<T, GenericOwningPointer>;
 /// **Non-movable** relocatable queue with runtime fixed size capacity.
-pub type RelocatableQueue<T> = details::MetaQueue<T, GenericRelocatablePointer>;
+pub type RelocatableQueue<T> = MetaQueue<T, GenericRelocatablePointer>;
 
 #[doc(hidden)]
-pub mod details {
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx2-bb/container/src/queue.rs:125]: Sorry for the huge diff. I didn't change the file content-wise, just removed the `details` module and used the type aliases where appropriate.

File: iceoryx2-bb/container/src/vec.rs
Comment (FerdinandSpitzschnueffler) [inline iceoryx2-bb/container/src/vec.rs:1]: Same here

File: iceoryx2-bb/container/src/slotmap.rs [hunk 2]
```diff
@@ -78,504 +78,503 @@ impl SlotMapKey {
 
 #[repr(C)]
 #[derive(Debug, Clone, Copy, ZeroCopySend)]
-struct FreeListEntry {
+pub(crate) struct FreeListEntry {
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx2-bb/container/src/slotmap.rs:81]: Same here + this struct is now pub

File: iceoryx2-bb/container/src/flatmap.rs [hunk 3]
```diff
@@ -48,10 +62,261 @@ struct Entry<K: Eq, V: Clone> {
...
+/// A runtime fixed-size, non-shared memory compatible [`FlatMap`]. The [`FlatMap`]s memory resides
+/// in the heap.
+pub type FlatMap<K, V> = MetaFlatMap<K, V, GenericOwningPointer>;
+
+/// A runtime fixed-size, shared-memory compatible [`RelocatableFlatMap`].
+pub type RelocatableFlatMap<K, V> = MetaFlatMap<K, V, GenericRelocatablePointer>;
+
+#[doc(hidden)]
+#[repr(C)]
+pub struct MetaFlatMap<K: Eq, V: Clone, Ptr: GenericPointer> {
```
Comment (elfenpiff) [inline iceoryx2-bb/container/src/flatmap.rs:74]: Can you please add a verify_init method like it is defined here for example: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/iceoryx2-bb/container/src/queue.rs#L335

and use it in every unsafe function that might cause undefined behavior when the container was not initialized, like here: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/iceoryx2-bb/container/src/queue.rs#L369

Comment (FerdinandSpitzschnueffler) [reply iceoryx2-bb/container/src/flatmap.rs:74]: I also added a check if `init()` was called more than once.

**Review by elfenpiff — APPROVED** [review]
