### PR TITLE
[#125] Fix reordering issue in 'spmc::UnrestrictedAtomic::load'

### LINKED ISSUE #125: Data race due to operation reordering in 'spmc::UnrestrictedAtomic::load'
## Required information

**Operating system:**
all

**Rust version:**
all

**Cargo version:**
all

**iceoryx2 version:**
`main` branch

**Observed result or behaviour:**

Reading from `data` in `load` can lead to a data race due to a reordering with the check to determine whether the write position changed.

**Expected result or behaviour:**

No reordering happens.

**Conditions where it occurred / Performed steps:**

Data race in the CI. Hard to reproduce.

CI failure on aarch64
```
test spmc_unrestricted_atomic_load_store_works_concurrently ... FAILED
failures:
---- spmc_unrestricted_atomic_load_store_works_concurrently stdout ----
thread '<unnamed>' panicked at iceoryx2-bb/lock-free/tests/spmc_unrestricted_atomic_tests.rs:102:21:
assertion failed: expr: verify_no_data_race(&sut.load()) == true;  value: false == true
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
thread 'spmc_unrestricted_atomic_load_store_works_concurrently' panicked at iceoryx2-bb/lock-free/tests/spmc_unrestricted_atomic_tests.rs:96:5:
a scoped thread panicked
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
failures:
    spmc_unrestricted_atomic_load_store_works_concurrently
```

### PR DESCRIPTION
**Pull request by elBoberido**
## Notes for Reviewer

The PR fixes a data race due to operation reordering in `spmc::UnrestrictedAtomic::load`

## Pre-Review Checklist for the PR Author

1. [x] Add sensible notes for the reviewer
1. [x] PR title is short, expressive and meaningful
1. [x] Relevant issues are linked
1. [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
1. [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Assign PR to reviewer
1. [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Unit tests have been written for new behavior
- [x] Public API is documented
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

Closes #125

### CODE REVIEW

File: iceoryx2-bb/lock-free/src/spmc/unrestricted_atomic.rs [hunk 1]
```diff
@@ -38,6 +38,8 @@ use std::{
     sync::atomic::{AtomicBool, AtomicU64, Ordering},
 };
 
+// ATTENTION: To ensure the functionality also in the case of an overflow wot the 'write_cell'
```
Comment (elfenpiff) [inline iceoryx2-bb/lock-free/src/spmc/unrestricted_atomic.rs:41]: What means `wot`?

**Review by elfenpiff — COMMENTED** [review]
There is a comment with a fantasy word, but besides from that everything looks great.

File: iceoryx2-bb/lock-free/src/spmc/unrestricted_atomic.rs (hunk 1 above)
Comment (elBoberido) [reply iceoryx2-bb/lock-free/src/spmc/unrestricted_atomic.rs:41]: That's scotch for "what". But you are right, it doesn't make sense in this context and should be "wi"

**Review by elfenpiff — APPROVED** [review]
