### PR TITLE
[#96] cleanup service of dead nodes

### LINKED ISSUE #96: Create decentralized service artifacts cleanup API
## (Code) Example Of Cumbersome API

Whenever an application crashes or is killed with `SIGKILL` all the resources are left behind. We need a decentral functionality to detect stale resources and clean them up.

So whenever an application is restarted  - typically during development - and detects old resources from a previous run, it automatically removes them.

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

1. [x] Add sensible notes for the reviewer
1. [x] PR title is short, expressive and meaningful
1. [x] Relevant issues are linked in the [References](#references) section
1. [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
1. [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Assign PR to reviewer
1. [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Unit tests have been written for new behavior
- [x] Public API is documented
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

Closes #96

### CODE REVIEW

File: iceoryx2/src/node/mod.rs [hunk 1]
```diff
@@ -344,13 +367,75 @@ impl<Service: service::Service> DeadNodeView<Service> {
...
+                }
+            }
+            CallbackProgression::Continue
+        };
+
+        match Node::<Service>::service_tags(config, self.id(), remove_node_from_service) {
+            Ok(()) => (),
+            Err(e) => {
+                IN_CLEANUP_SECTION.store(false, Ordering::Relaxed);
+                cleaner.abandon();
```
Comment (elBoberido) [inline iceoryx2/src/node/mod.rs:406]: Out of my ignorance this looks suspect. Should the order maybe be swapped?

File: iceoryx2/src/node/mod.rs [hunk 2]
```diff
@@ -344,13 +367,75 @@ impl<Service: service::Service> DeadNodeView<Service> {
...
+        };
+
+        match remove_node::<Service>(*self.id(), config) {
+            Ok(_) => {
+                IN_CLEANUP_SECTION.store(false, Ordering::Relaxed);
+                Ok(true)
+            }
+            Err(e) => {
+                IN_CLEANUP_SECTION.store(false, Ordering::Relaxed);
+                cleaner.abandon();
```
Comment (elBoberido) [inline iceoryx2/src/node/mod.rs:419]: Same here

Comment (elfenpiff) [reply iceoryx2/src/node/mod.rs:419]: Addressed, see previous comment

**Review by elBoberido — APPROVED** [review]
