### PR TITLE
[#162] refactor ipc capable trait

### LINKED ISSUE #162: Refactor `IpcCapable` trait
## Brief feature description

Currently, the `iceoryx2_bb_posix::IpcCapable` trait has too much responsibility for the layer it is located on. It shall not perform reference counting to ensure lifetime - what if the process crashes and the ref-count is unusable.
Furthermore, some resources shall persist even when no process is actively using them.

The solution is an `HandleStorage` that holds the handle, the handle itself destroys the resource in drop and the storage tracks if it is IpcCapable or not.

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

1. [x] Add sensible notes for the reviewer
1. [x] PR title is short, expressive and meaningful
1. [x] Relevant issues are linked in the [References](#references) section
1. [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
1. [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Assign PR to reviewer
1. [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Unit tests have been written for new behavior
- [x] Public API is documented
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [ ] All open points are addressed and tracked via issues

## References

Closes #162

### CODE REVIEW

File: iceoryx2-bb/posix/tests/semaphore_tests.rs [hunk 1]
```diff
@@ -418,46 +417,21 @@ fn unnamed_semaphore_multiple_ipc_semaphores_are_working() {
...
 }
 
 #[test]
+#[should_panic]
 fn unnamed_semaphore_acquiring_non_ipc_capable_handle_fails() {
     let handle = UnnamedSemaphoreHandle::new();
     let _sut1 = UnnamedSemaphoreBuilder::new()
         .is_interprocess_capable(false)
         .create(&handle)
         .unwrap();
```
Comment (elBoberido) [inline iceoryx2-bb/posix/tests/semaphore_tests.rs:434]:
```suggestion
    let _sut1 = UnnamedSemaphoreBuilder::new()
        .is_interprocess_capable(false)
        .create(&handle);
```

Just to prevent a false positive panic from `unwrap`

File: iceoryx2-bb/posix/src/ipc_capable.rs [hunk 2]
```diff
@@ -0,0 +1,175 @@
...
+        InterProcess,
+        ProcessLocal,
+    }
+
+    /// Stores an OS handle to some resource that is also inter-process capable, like a unnamed
+    /// semaphore or mutex handle.
+    pub struct HandleStorage<T> {
+        handle: UnsafeCell<T>,
+        is_inter_process_capable: AtomicBool,
+        state: AtomicBool,
```
Comment (elBoberido) [inline iceoryx2-bb/posix/src/ipc_capable.rs:34]: What does state mean in this context? `true`/`false` is not quite descriptive. What do you think of another name e.g. `active`, `initialized` or similar?

File: iceoryx2-bb/posix/src/ipc_capable.rs [hunk 3]
```diff
@@ -0,0 +1,175 @@
...
+            debug_assert!(
+                !self.state.load(Ordering::Relaxed),
+                "The handle must be uninitialized before it can be initialized."
+            );
+
+            self.is_inter_process_capable.store(
+                initializer(self.handle.get())? == Capability::InterProcess,
+                Ordering::Relaxed,
+            );
+            self.state.store(true, Ordering::Relaxed);
```
Comment (elBoberido) [inline iceoryx2-bb/posix/src/ipc_capable.rs:92]: A comment why `relaxed` is sufficient would be nice.

**Review by elBoberido — APPROVED** [review]

File: iceoryx2-bb/posix/src/barrier.rs [hunk 4]
```diff
@@ -153,54 +133,62 @@ impl BarrierBuilder {
                     "{} since an unknown error occurred ({}).", msg, v
                 );
             }
+        };
+
+        match self.is_interprocess_capable {
+            true => Ok(Capability::InterProcess),
+            false => Ok(Capability::ProcessLocal),
         }
```
[the remark this answers is not in the document]
Comment (elfenpiff) [reply iceoryx2-bb/posix/src/barrier.rs:141]: Yes, I would agree, but I like this more in this particular case.

**Review by elBoberido — DISMISSED** [review]

**Review by elBoberido — APPROVED** [review]
