### PR TITLE
[#1014] fix undefined behavior in user header

### LINKED ISSUE #1014: Undefined behavior in user header when loaning payload
**Observed result or behaviour:**
When a payload is loaned in the publisher, client or server and a custom user header is set, the user header is never constructed. This causes undefined behavior. The contract should be that the `UserHeader` must implement `Default` and that iceoryx2 always writes the default values into the sample.

Later, one could also think of an extended API where the user can provide the user header value when loaning data, but this is out of scope for this bug fix.

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * [x] Commit author matches [Eclipse Contributor Agreement][eca](and ECA is signed)
* [x] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [x] Assign PR to reviewer
* [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

* [x] Commits are properly organized and messages are according to the guideline
* [x] Unit tests have been written for new behavior
* [x] Public API is documented
* [x] PR title describes the changes

## Post-review Checklist for the PR Author

* [x] All open points are addressed and tracked via issues

## References

Closes #1014

### CODE REVIEW

File: iceoryx2-cxx/include/iox2/active_request.hpp [hunk 1]
```diff
@@ -175,6 +176,7 @@ ActiveRequest<Service, RequestPayload, RequestUserHeader, ResponsePayload, Respo
     ResponseMutUninit<Service, ResponsePayload, ResponseUserHeader> response;
     auto result = iox2_active_request_loan_slice_uninit(
         &m_handle, &response.m_response.m_response, &response.m_response.m_handle, NUMBER_OF_ELEMENTS);
+    internal::EmplaceNew<ResponseUserHeader>::emplace(response);
```
Comment (elBoberido) [inline iceoryx2-cxx/include/iox2/active_request.hpp]: This is not easy to understand what is going on. I had to look at the implementation. The naming is not ideal, since all the other `emplace` APIs take the actual data as parameter but here it's the reference to the underlying memory. Doesn't this more or less resemble `PlacementDefault`?

File: iceoryx2-cxx/include/iox2/internal/helper.hpp [hunk 2]
```diff
@@ -0,0 +1,35 @@
...
+#define IOX2_SERVICE_INTERNAL_HELPER_HPP
+
+namespace iox2::internal {
+template <typename T>
+struct EmplaceNew {
+    template <typename S>
+    static void emplace(S& payload) {
+        new (&payload.user_header_mut()) T();
+    }
+};
```
Comment (elBoberido) [inline iceoryx2-cxx/include/iox2/internal/helper.hpp]: Food for thought. I would suggest to not use the word `emplace` here, since no data is provided, but the reference to the memory. I would also propose to make this more generic by just expecting a `void*` as parameter and having only one generic parameter, e.g.

```cpp
template <typename T>
inline void placement_default(T* ptr) {
    new (ptr) T();
}

template <>
inline void placement_default(void*) {
}
```

This also shows via the signature that the dtor of the argument will not be called. The current implementation allows to call `emplace` multiple times and contrary to e.g. the `Optional` the dtor of the payload object is not called.

... oh, just realized that one would also need to implement `user_header_mut_ptr` in order to use the proposed API. I'll leave the comment here anyway.

**Review by elBoberido — COMMENTED** [review]
Looks good. Just some food for thought regarding the naming and potential invalid usage of the `EmplaceNew` API

**Review by elBoberido — DISMISSED** [review]

**Review by elBoberido — APPROVED** [review]
