### PR TITLE
[#1398] Fix double pthread_join

### LINKED ISSUE #1398: double `pthread_join` in scoped thread
**Observed result or behaviour:**
`pthread_join` is called twice on the same thread in scoped threads, leading to a segfault.

**Expected result or behaviour:**
Call `pthread_join` exactly once.

**Conditions where it occurred / Performed steps:**
When a thread is created in `thread_scope`

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * Keep in mind to use the same email that was used to sign the [Eclipse Contributor Agreement][eca]
* [x] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [x] Assign PR to reviewer
* [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## PR Reviewer Reminders

* Commits are properly organized and messages are according to the guideline
* Unit tests have been written for new behavior
* Public API is documented
* PR title describes the changes

## References

Closes #1398

### CODE REVIEW

File: iceoryx2-bb/posix/src/thread.rs [hunk 1]
```diff
@@ -666,6 +668,7 @@ pub trait ThreadProperties {
 pub struct ThreadHandle {
     handle: posix::pthread_t,
     name: UnsafeCell<ThreadName>,
+    is_joined: AtomicBool,
```
Comment (elBoberido) [inline iceoryx2-bb/posix/src/thread.rs]: Why an `AtomicBool`?

Also, wouldn't it make sense to just have an `Option<posix::pthread_t>` for the `handle`? AFAIK, with the current API, one can call `join()` and then `set_affinity()` on a dangling `handle` in the `ThreadHandle`.

Alternatively, just change the API to consume `self` in `join`. This might not simplify things, though, but at least communicates to the user that the object cannot be used anymore.

File: iceoryx2-bb/posix/src/thread.rs [hunk 2]
```diff
@@ -812,37 +845,12 @@ impl Debug for Thread {
...
     fn drop(&mut self) {
         warn!(from self,
-            when self.join(),
+            when self.handle.join(),
             "Unable to join thread that went out-of-scope.");
     }
 }
 
 impl Thread {
-    fn join(&self) -> Result<(), ThreadJoinError> {
```
Comment (elBoberido) [inline iceoryx2-bb/posix/src/thread.rs:821]: Wouldn't it make sense to keep the `join` method and just change the API to `join(self)`?
