### PR TITLE
[#888] Add end-to-end test for large data transfer over Zenoh tunnel

### LINKED ISSUE #888: Sending Large Data with Zenoh-Tunnel fails
## Required information

**Operating system:**

* OS name, version
- `Linux 6.12.22-1-rpi #1 SMP PREEMPT Fri Apr 11 06:09:22 MDT 2025 aarch64 GNU/Linux`
- `Linux 6.15.7-gentoo-dist #1 SMP PREEMPT_DYNAMIC Sat Jul 19 16:10:30 CEST 2025 x86_64 AMD Ryzen 9 9950X 16-Core Processor AuthenticAMD GNU/Linux`

**Rust version:**
Output of: `rustc 1.88.0`

**iceoryx2 version:**
`main` branch

**Conditions where it occurred / Performed steps:**
All pubsub and event examples work in combination with the zenoh tunnel where my Raspberry PI is connected to my desktop system, except the `complex_data_types` example.

When starting the zenoh tunnel and the example on both sides with
```
cargo run --bin iox2 -- tunnel-debug zenoh
cargo run --example complex_data_types
```
I just see the local communication but do not receive the remote samples. Looking at my network monitor reveals that a lot of data is communicated between both of them but the zenoh tunnel seems not be able to receive if on the other side.

The complex_data_types example sends samples that have a size of 33mb - which could be the underlying cause.

### PR DESCRIPTION
**Pull request by orecham**
## Notes for Reviewer

Adds an end-to-end test for large data transfer over the Zenoh tunnel utilizing the `ComplexDataType` struct from the `complex_data_types` example.

## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * [x] Commit author matches [Eclipse Contributor Agreement][eca](and ECA is signed)
* [x] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [x] Assign PR to reviewer
* [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

* [x] Commits are properly organized and messages are according to the guideline
* [x] Unit tests have been written for new behavior
* [x] Public API is documented
* [x] PR title describes the changes

## Post-review Checklist for the PR Author

* [x] All open points are addressed and tracked via issues

## References

Relates #888

### CODE REVIEW

**Comment by orecham** [comment]
@elfenpiff I was not able to reproduce the bug with this end-to-end test, but I would like to merge it for now just to prevent the effort of keeping it up to date with `main`. I will make another PR to fix the issue when I can reproduce and fix it. Could you approve this one?

File: iceoryx2-tunnels/end-to-end-tests/common/src/payload.rs [hunk 1]
```diff
@@ -0,0 +1,86 @@
...
+    #[allow(dead_code)]
+    unsafe fn write_payload(ptr: *mut Self::PayloadType);
+}
+
+pub struct PrimitivePayload;
+
+impl PayloadWriter for PrimitivePayload {
+    type PayloadType = u64;
+
+    unsafe fn write_payload(ptr: *mut Self::PayloadType) {
```
Comment (elfenpiff) [inline iceoryx2-tunnels/end-to-end-tests/common/src/payload.rs:44]: The ptr you are providing here, is it already initialized with a value, otherwise an assignment is undefined behavior and you must use `ptr.write(42)`

File: iceoryx2-tunnels/end-to-end-tests/ping-pong/src/pinger.rs [hunk 2]
```diff
@@ -0,0 +1,144 @@
...
+    let waitset = WaitSetBuilder::new().create::<ipc::Service>()?;
+
+    let pong_guard = waitset.attach_notification(&pong_listener)?;
+    let pong_id = WaitSetAttachmentId::from_guard(&pong_guard);
+
+    let timeout_guard = waitset.attach_interval(TIMEOUT_DURATION)?;
+    let timeout_id = WaitSetAttachmentId::from_guard(&timeout_guard);
+
+    // Create the payload on the heap
+    let mut payload_bytes = vec![0u8; std::mem::size_of::<P::PayloadType>()];
```
Comment (elfenpiff) [inline iceoryx2-tunnels/end-to-end-tests/ping-pong/src/pinger.rs]: Could you please rewrite this part to something like:

```rust
let ptr = unsafe { std::alloc::alloc(Layout::new::<MaybeUninit<P::PayloadType>>()) } as *mut MaybeUninit<P::PayloadType>;
unsafe { P::write_payload(ptr.cast()); }
// at the end you explicitly release it with
unsafe { std::alloc::dealloc(Layout::new::<MaybeUninit<P::PayloadType>>()) };
```

I think the memforget and then acquiring the `payload_ptr` from the vec into a Box seems like undefined behavior. Maybe there are other things to release we missed with `mem::forget` or the payload_ptr has an offset - this seems somehow cleaner.

File: iceoryx2-tunnels/end-to-end-tests/ping-pong/src/pinger.rs [hunk 3]
```diff
@@ -0,0 +1,144 @@
...
+        fail_test("Unexpected Event");
+    };
+
+    let ping_sample = ping_publisher.loan_uninit()?;
+
+    // The bytes of the payload are copied directly into shared memory, by-passing stack
+    unsafe {
+        std::ptr::copy_nonoverlapping(
+            payload.as_ref() as *const P::PayloadType as *const u8,
+            ping_sample.payload().as_ptr() as *mut u8,
```
Comment (elfenpiff) [inline iceoryx2-tunnels/end-to-end-tests/ping-pong/src/pinger.rs]: Please write `ping_sample.payload_mut().as_mut_ptr().cast()`

File: iceoryx2-tunnels/end-to-end-tests/ping-pong/src/ponger.rs [hunk 4]
```diff
@@ -0,0 +1,100 @@
...
+            ping_listener.try_wait_all(|_| {}).unwrap();
+
+            while let Ok(Some(ping_sample)) = ping_subscriber.receive() {
+                let pong_sample = pong_publisher.loan_uninit().unwrap();
+
+                // Copy the received ping payload directly into the pong payload, by-passing stack
+                unsafe {
+                    std::ptr::copy_nonoverlapping(
+                        ping_sample.payload() as *const P::PayloadType as *const u8,
+                        pong_sample.payload().as_ptr() as *mut u8,
```
Comment (elfenpiff) [inline iceoryx2-tunnels/end-to-end-tests/ping-pong/src/ponger.rs]: Please write `pong_sample.payload_mut().as_mut_ptr().cast()`

File: iceoryx2-tunnels/end-to-end-tests/ping-pong/src/ponger.rs [hunk 5]
```diff
@@ -0,0 +1,100 @@
...
+
+    let on_event = |id: WaitSetAttachmentId<ipc::Service>| {
+        if id == ping_id {
+            ping_listener.try_wait_all(|_| {}).unwrap();
+
+            while let Ok(Some(ping_sample)) = ping_subscriber.receive() {
+                let pong_sample = pong_publisher.loan_uninit().unwrap();
+
+                // Copy the received ping payload directly into the pong payload, by-passing stack
+                unsafe {
```
Comment (elfenpiff) [inline iceoryx2-tunnels/end-to-end-tests/ping-pong/src/ponger.rs:68]: I think you could also use `let initialized_pong_sample = pong_sample.write(ping.sample.payload().clone())` instead of the copy nonoverlapping

Comment (orecham) [reply iceoryx2-tunnels/end-to-end-tests/ping-pong/src/ponger.rs:68]: Doesn't work because the payload type need to implement Clone too, which is not true for the fields of the `ComplexType`.

**Review by elfenpiff — APPROVED** [review]
