### PR TITLE
[#140] fix freebsd

### LINKED ISSUE #140: Fix FreeBSD 14.0 build
## Required information

**Operating system:**
FreeBSD 14.0

**Rust version:**
rustc 1.76.0

**Cargo version:**
cargo 1.76.0

**iceoryx2 version:**
`main` branch

**Observed result or behaviour:**
The following tests fail:
* `event::unix_datagram::sending_multiple_notifications_from_multiple_sources_before_blocking_wait_works`
* `event::unix_datagram::sending_multiple_notifications_from_multiple_sources_before_timed_wait_works`
* `event::unix_datagram::sending_multiple_notifications_from_multiple_sources_before_try_wait_works`

And this test segfaults:
`shared_memory_directory::list_works`

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

1. [x] Add sensible notes for the reviewer
1. [x] PR title is short, expressive and meaningful
1. [x] Relevant issues are linked in the [References](#references) section
1. [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
1. [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Assign PR to reviewer
1. [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Unit tests have been written for new behavior
- [x] Public API is documented
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

Closes #140

### CODE REVIEW

File: iceoryx2-pal/posix/src/freebsd/mman.rs [hunk 1]
```diff
@@ -33,12 +38,95 @@ pub unsafe fn munlockall() -> int {
...
+        if *(name.add(i)) == 0i8 {
+            name_len = i;
+            break;
+        }
+    }
+
+    // suffix
+    for i in 0..suffix.len() {
+        state_file_path[i + SHM_STATE_DIRECTORY.len() + name_len] = suffix[i];
+    }
```
Comment (elBoberido) [inline iceoryx2-pal/posix/src/freebsd/mman.rs:72]:
```suggestion
    let start_index = SHM_STATE_DIRECTORY.len() + name_len;
    state_file_path[start_index..start_index+suffix.len()].copy_from_slice(&suffix);
```
No guarantees it will compile :)

File: iceoryx2-pal/posix/src/freebsd/mman.rs [hunk 2]
```diff
@@ -60,84 +148,52 @@ pub unsafe fn mprotect(addr: *mut void, len: size_t, prot: int) -> int {
...
-    ) == -1
-    {
-        return result;
+unsafe fn trim_ascii(value: &[i8]) -> &[u8] {
+    for i in 0..value.len() {
+        if value[i] == 0 {
+            return core::slice::from_raw_parts(value.as_ptr().cast(), i);
+        }
     }
+    core::slice::from_raw_parts(value.as_ptr().cast(), value.len())
```
Comment (elBoberido) [inline iceoryx2-pal/posix/src/freebsd/mman.rs:157]:
```suggestion
    let length = value.iter().position(|&c| c == 0).unwrap_or(value.len());
    core::slice::from_raw_parts(value.as_ptr().cast(), length)
```

**Review by elBoberido — APPROVED** [review]
Looks good. A few loops could be changed to iterators if you like :)

**Review by elBoberido — APPROVED** [review]
