### PR TITLE
[#262] Enable all tests on 32 bit

### LINKED ISSUE #262: Fully support C and C++ Bindings on 32 Bit Architectures
## Brief feature description

Currently the C bindings can be build on 32 bit but the out-of-tree builds do not work on the CI. The C++ bindings also do not work since `iceoryx_hoofs` is not yet ready for 32 bit support.

## Tasks

- [ ] out-of-tree builds for C Bindings on 32 bit
- [ ] C++ Bindings on 32 Bit (depends on `iceoryx_hoofs`)

### PR DESCRIPTION
**Pull request by elBoberido**
## Notes for Reviewer

After #1568 fixed the alignment issue with the `variant`, the 32 bit build also passed all tests, except a test for request response. But that test was wrong for 32 bit and this PR also adjusted the payload alignment tests.

## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * Keep in mind to use the same email that was used to sign the [Eclipse Contributor Agreement][eca]
* [x] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## PR Reviewer Reminders

* Commits are properly organized and messages are according to the guideline
* Unit tests have been written for new behavior
* Public API is documented
* PR title describes the changes

## References

Closes #262

### CODE REVIEW

File: iceoryx2-cxx/tests/src/service_request_response_tests.cpp [hunk 1]
```diff
@@ -853,17 +855,18 @@ TYPED_TEST(ServiceRequestResponseTest, setting_service_properties_works) {
                        .enable_fire_and_forget_requests(false)
                        .create()
                        .value();
+    std::cout << "aaaaargh: " << std::endl;
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx2-cxx/tests/src/service_request_response_tests.cpp]: I guess this line can be removed now 😁

File: iceoryx2-cxx/tests/src/service_request_response_tests.cpp [hunk 2]
```diff
@@ -831,11 +831,13 @@ TYPED_TEST(ServiceRequestResponseTest, setting_service_properties_works) {
...
     constexpr uint64_t MAX_LOANED_REQUESTS = 3;
-    constexpr uint64_t REQUEST_PAYLOAD_ALIGNMENT = 4;
-    constexpr uint64_t RESPONSE_PAYLOAD_ALIGNMENT = 8;
+    constexpr uint64_t REQUEST_PAYLOAD_ALIGNMENT = alignof(uint64_t) * 2;
+    constexpr uint64_t RESPONSE_PAYLOAD_ALIGNMENT = alignof(uint64_t) * 4;
 
     const auto service_name = iox2_testing::generate_service_name();
 
+
+    std::cout << "RESPONSE_PAYLOAD_ALIGNMENT: " << RESPONSE_PAYLOAD_ALIGNMENT << std::endl;
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx2-cxx/tests/src/service_request_response_tests.cpp]: Same here.

File: iceoryx2-cxx/tests/src/service_request_response_tests.cpp (hunk 1 above)
Comment (elBoberido) [reply iceoryx2-cxx/tests/src/service_request_response_tests.cpp]: No, I mean it :sweat_smile:

**Review by FerdinandSpitzschnueffler — APPROVED** [review]
