### PR TITLE
[#87] Fix undefined behavior in spsc {queue|index_queue}

### LINKED ISSUE #87: Undefined behavior in spsc fifo
## Required information

The `spsc::index_queue` and `spsc::queue` have undefined behavior in pop when there is a `self.read_position.store(.., Ordering::Release)` without a corresponding `Ordering::Acquire` on the same variable.

It was introduced to prevent statement reordering according to the as-if rule.

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

1. [x] Add sensible notes for the reviewer
1. [x] PR title is short, expressive and meaningful
1. [x] Relevant issues are linked
1. [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
1. [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Assign PR to reviewer
1. [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Unit tests have been written for new behavior
- [x] Public API is documented
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

Use either 'Closes #123' or 'Relates to #123' to reference the corresponding issue.

Closes #87

### CODE REVIEW

File: iceoryx2-bb/lock-free/src/spsc/queue.rs [hunk 1]
```diff
@@ -215,8 +215,11 @@ impl<T: Copy, const CAPACITY: usize> Queue<T, CAPACITY> {
                         .as_ptr()
                 };
 
+                // prevent that `out` and `read_position` statements are reordered according to
+                // the AS-IF rule.
+                core::sync::atomic::fence(Ordering::SeqCst);
                 self.read_position
-                    .store(current_read_pos + 1, Ordering::Release);
+                    .store(current_read_pos + 1, Ordering::Relaxed);
```
Comment (elBoberido) [inline iceoryx2-bb/lock-free/src/spsc/queue.rs:222]: It seems you ported this before my fix in https://github.com/eclipse-iceoryx/iceoryx/pull/1397.

I think the fence also works but need to check first since I'm not that familiar with fences and they work in a slightly different way then atomics.

Comment (elBoberido) [reply iceoryx2-bb/lock-free/src/spsc/queue.rs:222]: Not sure about that. I'm not even sure anymore the bugfix from `#1397` is correct, although miri did not complain when I checked it the last time. Maybe we need a session with @budrus @MatthiasKillat and @hrenkap

Comment (elfenpiff) [reply iceoryx2-bb/lock-free/src/spsc/queue.rs:222]: I think in this special case we really can use `AcqRel`, see https://www.modernescpp.com/index.php/fences-as-memory-barriers/

Only atomic load operations can be reordered to the top.

Comment (elBoberido) [reply iceoryx2-bb/lock-free/src/spsc/queue.rs:222]: I need to update my knowledge here. The blog post also talks about StoreLoad to have the capability of being reordered. I'm not quite sure if I still remember all of the tiny details which makes this stuff so tricky.

**Review by elBoberido — APPROVED** [review]
