### PR TITLE
[#314] fix deadlock in blocking publisher

### LINKED ISSUE #314: Dead lock in `UnableToDeliverStrategy::Block` when Subscriber is removed while Publisher Blocks
## Required information

See #305 

> The publisher blocks when there is a subscriber present when buffer gets filled. It also remains blocked when you remove the last subscriber before it consumes its buffer.

A publisher shall be unblocked when the subscriber, one which the publisher is waiting on, is removed.

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * Keep in mind to use the same email that was used to sign the [Eclipse Contributor Agreement][eca]
* [x] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## PR Reviewer Reminders

* Commits are properly organized and messages are according to the guideline
* Unit tests have been written for new behavior
* Public API is documented
* PR title describes the changes

## References

Closes #314

### CODE REVIEW

**Review by FerdinandSpitzschnueffler — APPROVED** [review]

File: iceoryx2-cal/src/zero_copy_connection/mod.rs [hunk 1]
```diff
@@ -173,7 +218,75 @@ pub trait ZeroCopyPortDetails {
...
+                CHANNEL_STATE_CLOSED.0,
+                state.0,
+                Ordering::Relaxed,
+                Ordering::Relaxed,
+            )
+            .is_ok()
+    }
+
+    fn set_disconnect_hint(&self, channel_id: ChannelId, expected_state: ChannelState) {
+        let disconnect_hint_state = expected_state.0 | CHANNEL_STATE_DISCONNECT_HINT_BIT;
```
Comment (elBoberido) [inline iceoryx2-cal/src/zero_copy_connection/mod.rs]: Since this pattern is used a few times. What do you think about lowering the cognitive load by adding this to the `ChannelState`

```rust
fn with_added_disconnect_hint(&self) -> Self {
    self | CHANNEL_STATE_DISCONNECT_HINT_BIT
}
```

This would make reading the code easier to understand, e.g. further down it would be
```rust
                expected_state.0,
                expected_state.with_added_disconnect_state(),
                Ordering::Relaxed,
                Ordering::Relaxed,
            );
```
