### PR TITLE
[#1405] fix pointer provenance in relocatable ptr

### LINKED ISSUE #1405: Fix pointer provenance in RelocatablePtr
`RelocatablePtr::as_ptr()` causes undefined behavior due to a pointer to integer cast that removes the underlying pointer provenance. When then the absolut pointer from the self position + offset is calculated a new pointer without any provenance is created.

This can be fixed by using the permissive provenance API ( `exposed_provenance` and `with_exposed_provenance`). The result would have the same provenance as the original version.

Miri is unable to detect this and prints a warning but with `MIRIFLAGS=-Zmiri-permissive-provenance cargo miri test` this can be mitigated

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * Keep in mind to use the same email that was used to sign the [Eclipse Contributor Agreement][eca]
* [x] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [x] Assign PR to reviewer
* [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## PR Reviewer Reminders

* Commits are properly organized and messages are according to the guideline
* Unit tests have been written for new behavior
* Public API is documented
* PR title describes the changes

## References

Closes #1405

### CODE REVIEW

File: iceoryx2-bb/elementary/src/relocatable_ptr.rs [hunk 1]
```diff
@@ -136,12 +136,15 @@ impl<T> RelocatablePointer<T> {
 
 impl<T> PointerTrait<T> for RelocatablePointer<T> {
     unsafe fn as_ptr(&self) -> *const T {
-        ((self as *const Self) as isize + self.distance.load(core::sync::atomic::Ordering::Relaxed))
-            as *const T
+        let base = (self as *const Self).expose_provenance();
+        let dist = self.distance.load(Ordering::Relaxed);
+        core::ptr::with_exposed_provenance(base.wrapping_add_signed(dist))
```
Comment (elBoberido) [inline iceoryx2-bb/elementary/src/relocatable_ptr.rs:141]: Not sure if this fully fixes the problem but it is a step in the right direction. For example, in the tests we often have e.g. a RelocatableVec and a [u8;N] which is then used with a `BumpAllocator`. In this case, the ReloacatablePrt is not from the same allocation as the pointer which is created. But if everything is placed in shared memory, this should be fine.

**Review by elBoberido — APPROVED** [review]

**Comment by elBoberido** [comment]
Oh, we need to switch to Ruts 1.84 ... maybe even Rust 1.85 so that we can use Edition 2024

File: iceoryx2-bb/elementary/src/relocatable_ptr.rs (hunk 1 above)
Comment (elBoberido) [reply iceoryx2-bb/elementary/src/relocatable_ptr.rs:141]: ... I take my remark with the tests back. That should still work with the provided API

**Comment by dkroenke** [comment]
> Oh, we need to switch to Ruts 1.84 ... maybe even Rust 1.85 so that we can use Edition 2024

@elBoberido Will be done in https://github.com/eclipse-iceoryx/iceoryx2/pull/1415

**Review by elBoberido — APPROVED** [review]

**Review by FerdinandSpitzschnueffler — APPROVED** [review]
