### PR TITLE
[#1383] Add iox2 service hz command

### LINKED ISSUE #1383: Add hz function in iceoryx2-cli like ROS2 topic hz
I'm currently planning to migrate my project from ROS2 DDS to Iceoryx2, and I'd like to have some cli tools supported by Iceoryx2 as well.

## Brief feature description

Add `hz` support in iox2 service

## Detailed information

- Quickly view the actual release frequency of a service (whether it meets expectations)

- Facilitate troubleshooting jitter, frame drops, and performance degradation

- Suitable for on-site debugging and regression testing

### PR DESCRIPTION
**Pull request by yumeminami**
## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * Keep in mind to use the same email that was used to sign the [Eclipse Contributor Agreement][eca]
* [x] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [x] Assign PR to reviewer
* [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## PR Reviewer Reminders

* Commits are properly organized and messages are according to the guideline
* Unit tests have been written for new behavior
* Public API is documented
* PR title describes the changes

## References

Closes #1383

 

## Summary
- add `iox2 service hz` command for publish-subscribe rate measurement
- include rolling statistics output (`rate_hz`, `avg_s`, `min_s`, `max_s`, `std_dev_s`, `window`)
- improve timeout behavior under queue drain and ensure final stats are emitted before timeout exit
- wait silently when service does not yet exist and start measuring once it appears
- add release-note entry for #1383

### CODE REVIEW

File: iceoryx2-cli/iox2-service/src/command/hz.rs [hunk 1]
```diff
@@ -0,0 +1,147 @@
+// Copyright (c) 2025 Contributors to the Eclipse Foundation
```
Comment (orecham) [inline iceoryx2-cli/iox2-service/src/command/hz.rs]:
```suggestion
// Copyright (c) 2026 Contributors to the Eclipse Foundation
```

**Review by orecham — COMMENTED** [review]
Looks sound. Is it possible to add an end-to-end test for this command? The exact values are not important, just that the command is properly detecting the service and outputting the stats.

BTW could you please re-add the PR template and tick off the items. It's a convention we would like to maintain for contributions.

**Comment by yumeminami** [comment]
> Looks sound. Is it possible to add an end-to-end test for this command? The exact values are not important, just that the command is properly detecting the service and outputting the stats.
> 
> 
> 
> BTW could you please re-add the PR template and tick off the items. It's a convention we would like to maintain for contributions.

@orecham I've added the e2e test and can you review it?

**Comment by orecham** [comment]
> @orecham I've added the e2e test and can you review it?

@yumeminami Perhaps a push is needed, can't see it in the diff :thinking:

**Comment by yumeminami** [comment]
> > @orecham I've added the e2e test and can you review it?
> 
> @yumeminami Perhaps a push is needed, can't see it in the diff 🤔

@orecham sry, I push the commit to the wrong branch, now the commit f60728325aef675a11f22f7253cd3fe5fad7392b could be review

**Comment by orecham** [comment]
@yumeminami Thanks for the contribution! This is a great addition.
