### PR TITLE
[#1252] fix cleanup issue

### LINKED ISSUE #1252: iceoryx2 monitoring concept does not remove owner_lock
**Observed result or behaviour:**
When the monitoring concept file lock implementation is explicitly removed, for instance during cleanup, with `remove()` the `_owner_lock` file is not removed. 

**Expected result or behaviour:**
All files from the monitoring concept are removed.

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * Keep in mind to use the same email that was used to sign the [Eclipse Contributor Agreement][eca]
* [x] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [x] Assign PR to reviewer
* [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## PR Reviewer Reminders

* Commits are properly organized and messages are according to the guideline
* Unit tests have been written for new behavior
* Public API is documented
* PR title describes the changes

## References

Closes #1252

### CODE REVIEW

File: iceoryx2-bb/posix/src/process_state.rs [hunk 1]
```diff
@@ -519,6 +519,45 @@ fn generate_owner_lock_path(path: &FilePath) -> Result<FilePath, SemanticStringE
 }
 
 impl ProcessGuard {
+    /// Removes by force an existing [`ProcessGuard`]. This useful when stale resources of a dead process
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx2-bb/posix/src/process_state.rs]:
```suggestion
    /// Removes by force an existing [`ProcessGuard`]. This is useful when stale resources of a dead process
```

File: iceoryx2-bb/posix/src/process_state.rs [hunk 2]
```diff
@@ -519,6 +519,45 @@ fn generate_owner_lock_path(path: &FilePath) -> Result<FilePath, SemanticStringE
...
+    /// need to be cleaned up.
+    ///
+    /// # Safety
+    ///
+    ///  - User must ensure that no [`Process`](crate::process::Process) currently has an instance of
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx2-bb/posix/src/process_state.rs]:
```suggestion
    ///  - Users must ensure that no [`Process`](crate::process::Process) currently has an instance of
```

File: iceoryx2/tests/service_event_thread_safety_tests.rs [hunk 3]
```diff
@@ -79,7 +79,6 @@ fn notifying_events_concurrently_works() {
         // ensure all events are read
         while let Ok(Some(event)) = listener.try_wait_one() {
             received_events[event.as_value()] += 1;
-            total_received_events += 1;
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx2/tests/service_event_thread_safety_tests.rs:82]: Why was this removed?

Comment (elfenpiff) [reply iceoryx2/tests/service_event_thread_safety_tests.rs:82]: total_received_events was no longer used in this test. clippy found it, so i removed it

**Review by FerdinandSpitzschnueffler — APPROVED** [review]
