### PR TITLE
[#1455] Fix 'timer_create' on FreeBSD

### LINKED ISSUE #1455: Nightly failing on FreeBSD
## Required information

**Operating system:** FreeBSD 15.0

**Rust version:** 1.94.0

**iceoryx2 version:** main

**Detailed log output:**

```
  error[E0425]: cannot find value `os_specific_buffer` in this scope
    --> iceoryx2-pal/posix/src/freebsd/timer.rs:23:50
     |
  23 |     crate::internal::timer_create(clock_id, &mut os_specific_buffer, timer_id)
     |                                                  ^^^^^^^^^^^^^^^^^^ not found in this scope
```

**Observed result or behaviour:**
https://github.com/eclipse-iceoryx/iceoryx2/actions/runs/23224944240/job/67505882631

**Expected result or behaviour:**
Build is passing on FreeBSD

**Conditions where it occurred / Performed steps:**
Compile iceoryx2-pal-posix on FreeBSD 15

### PR DESCRIPTION
**Pull request by elBoberido**
## Notes for Reviewer

Fix copy&paste error introduced with `timer_create`.

The branch was manually triggered on the nightly CI -> https://github.com/eclipse-iceoryx/iceoryx2/actions/runs/23267655399

## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * Keep in mind to use the same email that was used to sign the [Eclipse Contributor Agreement][eca]
* [~] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## PR Reviewer Reminders

* Commits are properly organized and messages are according to the guideline
* Unit tests have been written for new behavior
* Public API is documented
* PR title describes the changes

## References

Closes #1455

### CODE REVIEW

File: iceoryx2-pal/posix/src/freebsd/timer.rs [hunk 1]
```diff
@@ -20,7 +20,7 @@ pub unsafe fn timer_create(
     sevp: *mut sigevent,
     timer_id: *mut timer_t,
 ) -> int {
-    crate::internal::timer_create(clock_id, &mut os_specific_buffer, timer_id)
+    crate::internal::timer_create(clock_id, sevp, timer_id)
```
Comment (orecham) [inline iceoryx2-pal/posix/src/freebsd/timer.rs:23]: ugh, a copy-paste error, my bad

**Review by orecham — DISMISSED** [review]

**Review by orecham — APPROVED** [review]
