### PR TITLE
[#437] Fix misleading warning related to default config file

### LINKED ISSUE #437: Warning regarding default config is misleading
## Required information

**Operating system:**

any

**Rust version:**

any

**Cargo version:**

any

**iceoryx2 version:**
E.g. `v1.2.3` or `main` branch

- `v0.4.1`
- `main`

**Detailed log output:**

```
        2 [W] "Config::global_config()"
              | Default config file found but unable to read data, populate config with default values.
```

**Observed result or behaviour:**

When running an iceoryx2 application, it looks for `config/iceoryx2.toml`. When it is not found, it prints the warning from above. This is misleading, since the config is not found. 

**Expected result or behaviour:**

The warning should not be printed when the config file was not found but only when it was found and and could not be read.

**Conditions where it occurred / Performed steps:**

Create an out-of-tree iceoryx2 application and run it.

### PR DESCRIPTION
**Pull request by elBoberido**
## Notes for Reviewer

This PR fixes a misleading warning related to the default config file. If the file was not found in the first place, only a debug message is printed. Only when the file is found and could not be processed, the warning is printed.

See related issue for more information.

## Pre-Review Checklist for the PR Author

1. [x] Add sensible notes for the reviewer
1. [x] PR title is short, expressive and meaningful
1. [x] Relevant issues are linked in the [References](#references) section
1. [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
1. [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Assign PR to reviewer
1. [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Unit tests have been written for new behavior
- [x] Public API is documented
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

Closes #437

### CODE REVIEW

**Review by elfenpiff — APPROVED** [review]

File: iceoryx2/src/config.rs [hunk 1]
```diff
@@ -395,14 +395,24 @@ impl Config {
     /// is called after this function was called, no file will be loaded since the global default
     /// config was already populated.
     pub fn global_config() -> &'static Config {
-        if !ICEORYX2_CONFIG.is_initialized()
-            && Config::setup_global_config_from_file(unsafe {
+        if !ICEORYX2_CONFIG.is_initialized() {
+            match Config::setup_global_config_from_file(unsafe {
                 &FilePath::new_unchecked(DEFAULT_CONFIG_FILE)
```
Comment (orecham) [inline iceoryx2/src/config.rs:400]: Can we put the default config in a standard location? This would be useful for the `iox2 config` CLI too.

Comment (elBoberido) [reply iceoryx2/src/config.rs:400]: Agreed. See also https://github.com/eclipse-iceoryx/iceoryx2/issues/437#issuecomment-2395451559

I would create a separate PR for this though. This PR could be part of a v0.4.2 release

Comment (elBoberido) [reply iceoryx2/src/config.rs:400]: See #442
