### PR TITLE
[#61] fix undefined behavior in string

### LINKED ISSUE #61: Undefined behavior in `FixedSizeByteString`
## Required information

See: https://play.rust-lang.org/?version=stable&mode=debug&edition=2021&gist=6e9853859e64c36ddfe4ce821f96bd3b

### PR DESCRIPTION
**Pull request by elfenpiff**
## Notes for Reviewer

Just turn `FixedSizeByteString::new_unchecked` into a non-const function. As it turned out, it had some impact to the concept layer.

## Pre-Review Checklist for the PR Author

1. [x] Add sensible notes for the reviewer
1. [x] PR title is short, expressive and meaningful
1. [x] Relevant issues are linked
1. [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
1. [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Assign PR to reviewer
1. [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Unit tests have been written for new behavior
- [x] Public API is documented
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

Use either 'Closes #123' or 'Relates to #123' to reference the corresponding issue.

Closes #61

### CODE REVIEW

File: iceoryx2-cal/src/communication_channel/message_queue.rs [hunk 1]
```diff
@@ -138,23 +138,25 @@ impl<T: Copy + Debug> CommunicationChannel<T> for Channel<T> {
 }
 
 #[derive(Clone, Copy, PartialEq, Eq, Debug)]
-pub struct Configuration {
+pub struct Configuration<T: Copy + Debug> {
```
Comment (elBoberido) [inline iceoryx2-cal/src/communication_channel/message_queue.rs:141]: Out of curiosity, why was this changed required?

If it is just to be able to call `Channel::<T>::default_*()` it would also work with `Channel::<()>::default_*()`.

Or alternatively just replacing the constants with free functions would also work without having to add generic parameter all over the place.

Comment (elfenpiff) [reply iceoryx2-cal/src/communication_channel/message_queue.rs]: There was actually no need for it and I removed it again.

Comment (elBoberido) [reply iceoryx2-cal/src/communication_channel/message_queue.rs]: Weird, I still see the generic parameter in the diff

Comment (elfenpiff) [reply iceoryx2-cal/src/communication_channel/message_queue.rs]: Whoopsie my mistake. I need more sleep :/

**Review by elBoberido — APPROVED** [review]
