### PR TITLE
[#1356] fix mem order

### LINKED ISSUE #1356: Fix memory order in queues and producer/consumer acquiring
1. IndexQueue. Introduce second sync-point to ensure that the data is never read when it is written byt the producer.
2. It is possible that `pop` and `push` is performed on multiple threads. Therefore, the user has to release the producer/consumer guard and another thread needs to acquire it. Here we need seqcst ordering to ensure that the read/write position updates of the previous thread happened before the release and reacquire of the guards in another thread.

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * Keep in mind to use the same email that was used to sign the [Eclipse Contributor Agreement][eca]
* [x] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [x] Assign PR to reviewer
* [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## PR Reviewer Reminders

* Commits are properly organized and messages are according to the guideline
* Unit tests have been written for new behavior
* Public API is documented
* PR title describes the changes

## References

Closes #1356

### CODE REVIEW

**Comment by elfenpiff** [comment]
review ping @ComicSansMS

File: iceoryx2-bb/lock-free/src/spmc/unrestricted_atomic.rs [hunk 1]
```diff
@@ -84,7 +84,7 @@ impl<T: Copy> Producer<'_, T> {
 
 impl<T: Copy> Drop for Producer<'_, T> {
     fn drop(&mut self) {
-        self.atomic.mgmt.has_producer.store(true, Ordering::Relaxed);
+        self.atomic.mgmt.has_producer.store(true, Ordering::SeqCst);
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx2-bb/lock-free/src/spmc/unrestricted_atomic.rs]: I can already see our future selves looking skeptically on the memory order. Can you please comment why sequentially consistent is needed? As this seems needed everywhere we have a producer/consumer guard, this comment could go to a more central place (lib.rs?) and then we refer to it in every relevant lock-free construct.

File: iceoryx2-bb/lock-free/src/spsc/safely_overflowing_index_queue.rs [hunk 2]
```diff
@@ -97,7 +102,12 @@ impl<PointerType: PointerTrait<UnsafeCell<u64>> + Debug> Consumer<'_, PointerTyp
 
 impl<PointerType: PointerTrait<UnsafeCell<u64>>> Drop for Consumer<'_, PointerType> {
     fn drop(&mut self) {
-        self.queue.has_consumer.store(true, Ordering::Relaxed);
+        self.queue.has_consumer.store(
+            true,
+            // SYNC POINT: consumer
+            // sync the internal state with the next consumer in another thread
+            Ordering::SeqCst,
```
Comment (FerdinandSpitzschnueffler) [inline iceoryx2-bb/lock-free/src/spsc/safely_overflowing_index_queue.rs]:
```suggestion
            Ordering::Release,
```
