### PR TITLE
Iox2 947 fix memory leak when port creation fails

### LINKED ISSUE #947: Memory leak when port creation fails in C
Before posting the bug, take a look at the
[FAQ](https://github.com/eclipse-iceoryx/iceoryx2/blob/main/FAQ.md)
for a possible solution.

## Required information

**iceoryx2 version:**
`main` branch

**Detailed log output:**
==31162==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 288 byte(s) in 1 object(s) allocated from:
    #0 0x7f1af4720cb5 in malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:67
    #1 0x55e180b56eff in iox2_port_factory_publisher_builder_create 
    #2 0x55e17fe31171 in (anonymous namespace)::ServicePublishSubscribeTest_only_max_publishers_can_be_created_Test<iox2_testing::TypeServiceType<(iox2::ServiceType)0> >::TestBody() 
...
Direct leak of 288 byte(s) in 1 object(s) allocated from:
    #0 0x7f1af4720cb5 in malloc /usr/src/debug/gcc/gcc/libsanitizer/asan/asan_malloc_linux.cpp:67
    #1 0x55e180b56eff in iox2_port_factory_publisher_builder_create 
    #2 0x55e17fe35593 in (anonymous namespace)::ServicePublishSubscribeTest_only_max_publishers_can_be_created_Test<iox2_testing::TypeServiceType<(iox2::ServiceType)1> >::TestBody() 
...

SUMMARY: AddressSanitizer: 576 byte(s) leaked in 2 allocation(s).

**Observed result or behaviour:**
A memory leak occurs when a publisher cannot be created, see example below. The same goes for the subscriber, client, server, listener, and notifier.

```
TYPED_TEST(ServicePublishSubscribeTest, only_max_publishers_can_be_created) {
    constexpr ServiceType SERVICE_TYPE = TestFixture::TYPE;

    const auto service_name = iox2_testing::generate_service_name();

    auto node = NodeBuilder().create<SERVICE_TYPE>().expect("");
    auto service = node.service_builder(service_name)
                       .template publish_subscribe<uint64_t>()
                       .max_publishers(1)
                       .create()
                       .expect("");
    auto publisher = iox::optional<Publisher<SERVICE_TYPE, uint64_t, void>>(service.publisher_builder().create().expect(""));

    auto failing_sut = service.publisher_builder().create();
    ASSERT_TRUE(failing_sut.has_error());

    publisher.reset();

    auto sut = service.publisher_builder().create();
    ASSERT_FALSE(sut.has_error());
}
```

**Expected result or behaviour:**
no memory leaks

**Conditions where it occurred / Performed steps:**
Run above examples with sanitizers.

### PR DESCRIPTION
**Pull request by FerdinandSpitzschnueffler**
## Notes for Reviewer

see title

## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * [x] Commit author matches [Eclipse Contributor Agreement][eca](and ECA is signed)
* [x] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [x] Assign PR to reviewer
* [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

* [ ] Commits are properly organized and messages are according to the guideline
* [ ] Unit tests have been written for new behavior
* [ ] Public API is documented
* [ ] PR title describes the changes

## Post-review Checklist for the PR Author

* [x] All open points are addressed and tracked via issues

## References

Closes #947

### CODE REVIEW

File: iceoryx2-ffi/cxx/tests/src/service_event_tests.cpp [hunk 1]
```diff
@@ -793,4 +793,40 @@ TYPED_TEST(ServiceEventTest, listener_details_are_correct) {
...
 }
+
+TYPED_TEST(ServiceEventTest, only_max_notifiers_can_be_created) {
+    constexpr ServiceType SERVICE_TYPE = TestFixture::TYPE;
+
+    const auto service_name = iox2_testing::generate_service_name();
+
+    auto node = NodeBuilder().create<SERVICE_TYPE>().expect("");
+    auto service = node.service_builder(service_name).event().max_notifiers(1).create().expect("");
+    auto notifier = iox::optional<Notifier<SERVICE_TYPE>>(service.notifier_builder().create().expect(""));
```
Comment (elBoberido) [inline iceoryx2-ffi/cxx/tests/src/service_event_tests.cpp:804]: We need a `iox::make_optional` to reduce the amount of typing :)

**Review by elBoberido — APPROVED** [review]
