### PR TITLE
[#287] fix directory mem leak

### LINKED ISSUE #287: Mem-leak in `iceoryx2_bb_posix::Directory::contents()` on failure
## Required information

When the `contents` call fails, it will immediately return with `fail!` and skip the release of the acquired memory `posix::free` for the file names.

### PR DESCRIPTION
**Pull request by elfenpiff**
## Pre-Review Checklist for the PR Author

1. [x] Add sensible notes for the reviewer
1. [x] PR title is short, expressive and meaningful
1. [x] Relevant issues are linked in the [References](#references) section
1. [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
1. [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
1. [x] Commits messages are according to this [guideline][commit-guidelines]
    - [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    - [x] Commit author matches [Eclipse Contributor Agreement][eca] (and ECA is signed)
1. [x] Tests follow the [best practice for testing][testing]
1. [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
1. [x] Assign PR to reviewer
1. [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

- [x] Commits are properly organized and messages are according to the guideline
- [x] Unit tests have been written for new behavior
- [x] Public API is documented
- [x] PR title describes the changes

## Post-review Checklist for the PR Author

1. [x] All open points are addressed and tracked via issues

## References

Closes #287

### CODE REVIEW

File: iceoryx2-bb/posix/src/directory.rs [hunk 1]
```diff
@@ -379,64 +380,76 @@ impl Directory {
...
-                let raw_name = unsafe {
-                    (*(*namelist.offset(i as isize))).d_name.as_ptr() as *mut posix::c_char
-                };
-                let raw_name_length = unsafe { strnlen(raw_name, FileName::max_len()) };
-
-                const DOT: posix::c_char = b'.' as _;
-                // dot is skipped
-                if raw_name_length == 1 && unsafe { *raw_name == DOT } {
-                    continue;
+        let _memory_cleanup_guard = ScopeGuardBuilder::new(namelist)
```
Comment (elBoberido) [inline iceoryx2-bb/posix/src/directory.rs:383]: Nice, something like this would also be great for the C bindings but I need to discard the drop on the happy path. Need to look at the API how easily this can be done. Maybe we need something which builds upon the `ScopeGuard`, e.g. `CleanupGuard` which has an `ok()` (or similar) method to discard the cleanup callback

**Review by elBoberido — APPROVED** [review]
