### PR TITLE
[#1116] Fix QNX cross compilation

### LINKED ISSUE #1116: QNX cross compilation broken
## Required information

**Operating system:**

QNX

**Rust version:**

any

**Cargo version:**

any

**iceoryx2 version:**

`main` branch (post v0.7.0)

The bug was introduced with the epoll support.

**Observed result or behaviour:**

When cross compiling QNX on Linux, cargo tries to build the epoll supports and fails.

**Expected result or behaviour:**

Do not build epoll on QNX.

**Conditions where it occurred / Performed steps:**

Cross compile iceoryx2 for QNX on Linux.

The problem is that the the `build.rs` file is build for the host OS. This means that `target_os = "linux"` does not work in order to prevent the compilation of the epoll support when cross compiling from Linux.

One needs to check the cargo `TARGET` env variable to determine the actual target OS for cross compilation.

This means, both needs to be used, `target_os = "linux"`, e.g. to prevent pulling in a dependency like bindgen for native compilation and the `TARGET` env variable, to prevent to build the `build.rs` during cross compilation.

### PR DESCRIPTION
**Pull request by elBoberido**
## Notes for Reviewer

The introduction of epoll on Linux broke the QNX cross compilation from Linux.

## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * [x] Commit author matches [Eclipse Contributor Agreement][eca](and ECA is signed)
* [~] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [x] Assign PR to reviewer
* [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

* [x] Commits are properly organized and messages are according to the guideline
* [x] Unit tests have been written for new behavior
* [x] Public API is documented
* [x] PR title describes the changes

## Post-review Checklist for the PR Author

* [x] All open points are addressed and tracked via issues

## References

Closes #1116

### CODE REVIEW

File: iceoryx2-pal/os-api/build.rs [hunk 1]
```diff
@@ -13,36 +13,44 @@
...
-        .use_core();
-
-    if std::env::var("DOCS_RS").is_ok() {
-        builder = builder.clang_arg("-D IOX2_DOCS_RS_SUPPORT");
+    // when cross compiling, 'target_os' is set to the environment the build script
+    // is executed; to get the actual target OS, use the cargo 'TARGET' env variable
+    let target = std::env::var("TARGET").unwrap();
+    println!("Building for target: {}", target);
+
+    // the check for 'vxworks' in the next line refers to native compilation
```
Comment (orecham) [inline iceoryx2-pal/os-api/build.rs]:
```suggestion
    // the check for 'linux' in the next line refers to native compilation
```

File: iceoryx2-pal/os-api/build.rs [hunk 2]
```diff
@@ -13,36 +13,44 @@
...
+    // and prevents to pull in bindgen
+    #[cfg(target_os = "linux")]
+    // the check for 'vxworks' in the next line refers to cross compilation
```
Comment (orecham) [inline iceoryx2-pal/os-api/build.rs]:
```suggestion
    // the check for 'linux' in the next line refers to cross compilation
```

**Review by orecham — DISMISSED** [review]

**Review by orecham — APPROVED** [review]
