### PR TITLE
iox-1163: Fix QNX8 builds

### LINKED ISSUE #1163: QNX8 build does not work
Before posting the bug, take a look at the
[FAQ](https://github.com/eclipse-iceoryx/iceoryx2/blob/main/FAQ.md)
for a possible solution.

## Required information

**Operating system:**

* OS name, version
* Additionally, on Linux, Mac Os, Unix, output of: `uname -a`
* Additionally, on Windows, output of: `ver`

**Rust version:**
Output of: `rustc --version`

**Cargo version:**
Output of: `cargo --version`

**iceoryx2 version:**
E.g. `v1.2.3` or `main` branch

**Detailed log output:**
Add the call `set_log_level(LogLevel::Trace)` at the beginning of your application
and attach the detailed log-output to the bug ticket.

**Observed result or behaviour:**
A minimalistic running code example that reproduces the bug or
a clear and precise description of the observed result.

**Expected result or behaviour:**
What do you expect to happen?

**Conditions where it occurred / Performed steps:**
Describe how one can reproduce the bug.

### PR DESCRIPTION
**Pull request by pawelrutkaq**
The posix pal for QNX now uses internal
type sync_t from bindgen. In QNX8 the type aliasing is different. Start using public alias for posix types from bindgen

## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * [x] Commit author matches [Eclipse Contributor Agreement][eca](and ECA is signed)
* [x] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [x] Assign PR to reviewer
* [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

* [x] Commits are properly organized and messages are according to the guideline
* [x] Unit tests have been written for new behavior
* [x] Public API is documented
* [x] PR title describes the changes

## Post-review Checklist for the PR Author

* [x] All open points are addressed and tracked via issues

## References

Closes #1163

### CODE REVIEW

File: iceoryx2-pal/posix/src/qnx/types.rs [hunk 1]
```diff
@@ -91,11 +90,13 @@ pub type pthread_rwlockattr_t = sync_attr_t;
 pub type pthread_rwlock_t = crate::internal::pthread_rwlock_t;
 impl MemZeroedStruct for pthread_rwlock_t {}
 
-pub type pthread_mutex_t = sync_t;
+pub type pthread_mutex_t = crate::internal::pthread_mutex_t;
```
Comment (orecham) [inline iceoryx2-pal/posix/src/qnx/types.rs:91]: Was this verified on both QNX 8 and QNX 7.1?

File: iceoryx2-pal/posix/src/qnx/types.rs [hunk 2]
```diff
@@ -91,11 +90,13 @@ pub type pthread_rwlockattr_t = sync_attr_t;
...
+impl MemZeroedStruct for pthread_mutex_t {}
 
 pub type pthread_mutexattr_t = sync_attr_t;
 
-pub type sem_t = sync_t;
+pub type sem_t = crate::internal::sem_t;
+impl MemZeroedStruct for sem_t {}
```
Comment (elBoberido) [inline iceoryx2-pal/posix/src/qnx/types.rs:100]: On QNX 7.1, there is a "conflicting implementation" error for `sem_t`. It seems `sem_t` and `pthread_mutex_t` are a typedef to the same `_sync`

File: iceoryx2-pal/posix/src/qnx/types.rs [hunk 3]
```diff
@@ -67,7 +67,6 @@ pub type pthread_barrier_t = crate::internal::pthread_barrier_t;
 impl MemZeroedStruct for pthread_barrier_t {}
 
 pub type sync_t = crate::internal::sync_t;
```
Comment (elBoberido) [inline iceoryx2-pal/posix/src/qnx/types.rs]: This can also be removed. I is only used for the `pthread_mutex_t` and `sem_t` typedefs

File: iceoryx2-pal/posix/src/qnx/types.rs [hunk 4]
```diff
@@ -91,11 +90,13 @@ pub type pthread_rwlockattr_t = sync_attr_t;
...
 impl MemZeroedStruct for pthread_rwlock_t {}
 
-pub type pthread_mutex_t = sync_t;
+pub type pthread_mutex_t = crate::internal::pthread_mutex_t;
+impl MemZeroedStruct for pthread_mutex_t {}
 
 pub type pthread_mutexattr_t = sync_attr_t;
 
-pub type sem_t = sync_t;
+pub type sem_t = crate::internal::sem_t;
```
Comment (orecham) [inline iceoryx2-pal/posix/src/qnx/types.rs:96]: You will probably need to do something like this for these changes:

```suggestion
#[cfg(target_env = "nto71")]
pub type sem_t = sync_t;
#[cfg(target_env = "nto80")]
pub type sem_t = crate::internal::sem_t;
```

File: iceoryx2-pal/posix/src/qnx/types.rs (hunk 1 above)
Comment (orecham) [reply iceoryx2-pal/posix/src/qnx/types.rs:91]: Before merging, we need to somehow confirm that QNX 7.1 still builds with the changes applied. I currently do not have a license to do so unfortunately.

File: iceoryx2-pal/posix/src/qnx/types.rs (hunk 3 above)
Comment (orecham) [reply iceoryx2-pal/posix/src/qnx/types.rs]: I guess we need to keep it for the QNX 7.1 build.

Comment (elBoberido) [reply iceoryx2-pal/posix/src/qnx/types.rs]: No, it works for QNX 7.1. The problem is only the "conflicting implementation" for `sem_t` and `pthread_mutex_t`, because they are a typedef to the same `_sync`

Comment (pawelrutkaq) [reply iceoryx2-pal/posix/src/qnx/types.rs]: So the problem is this MemZeroedStruct  thing at the end. Question: So how do we proceed :

1. implement it only for internal types, _sync, sync_mutex and not for aliases (still requires feature cfg gate)
2. feature  cfg gates on certain types.

Comment (orecham) [reply iceoryx2-pal/posix/src/qnx/types.rs]: I have no preference, feel free to propose something

File: iceoryx2-pal/posix/src/qnx/types.rs (hunk 2 above)
Comment (pawelrutkaq) [reply iceoryx2-pal/posix/src/qnx/types.rs:100]: shall be done

File: iceoryx2-pal/posix/src/qnx/types.rs (hunk 3 above)
Comment (pawelrutkaq) [reply iceoryx2-pal/posix/src/qnx/types.rs]: shall be done

File: iceoryx2-pal/posix/src/qnx/types.rs (hunk 4 above)
Comment (pawelrutkaq) [reply iceoryx2-pal/posix/src/qnx/types.rs:96]: shall be done

File: iceoryx2-pal/posix/src/qnx/types.rs (hunk 1 above)
Comment (pawelrutkaq) [reply iceoryx2-pal/posix/src/qnx/types.rs:91]: For QNX8 its building. For 7.1 we need to ask @elBoberido

**Comment by pawelrutkaq** [comment]
@orecham @elBoberido can you relook ?

**Comment by elBoberido** [comment]
@pawelrutkaq  I need to check if this still works with QNX 7.1. If I do not manage to test it today, it will be done on Monday next week.
