### PR TITLE
[#992] fix bumpallocator provenance

### LINKED ISSUE #991: bb-elementary BumpAllocator must not be Sync
## Required information

**iceoryx2 version:** `main` branch (commit: d40bbf0e)

**Problem description:**
`iceoryx2_bb_elementary::bump_allocator::BumpAllocator` is `Sync` (auto-derived), but this part in `allocate()` is not thread-safe:

```rust
        let mem = align(self.pos.load(Ordering::Relaxed), layout.align());
        self.pos.store(mem + layout.size(), Ordering::Relaxed);
```

Since `allocate()` takes `&self`, multiple threads can call this method concurrently and reserve overlapping memory regions.

**Solutions:**

1. Use `compare_exchange` in a loop to make the update on `self.pos` atomic.
2. Add `_marker: PhantomData<Cell<usize>>` to make `BumpAllocator: !Sync`. Or better yet, use `pos: Cell<usize>`, which automatically makes it `!Sync` but still `Send`.

### LINKED ISSUE #992: bb-elementary BumpAllocator loses provenance of reserved memory
`iceoryx2_bb_elementary::bump_allocator::BumpAllocator` uses `usize` and `IoxAtomicUsize` to keep track of the start and current position of the memory area:

```rust
pub struct BumpAllocator {
    start: usize,
    pos: IoxAtomicUsize,
}
```

Unfortunately, this means that miri will flag this code:

```rust
core::slice::from_raw_parts_mut(mem as *mut u8, layout.size())
```

with a *Stacked Borrows* violation.

## Improvement Suggestion

Is there a specific reason why the allocator uses integers instead of pointers for `start` and `pos`? If not, it should be possible to change that to `AtomicPtr` (or even `AtomicUsize`, see #991), so that miri can properly track the provenance of the derived pointers.

### PR DESCRIPTION
**Pull request by elfenpiff**
## Notes for Reviewer

Adjust the `new` start argument type to `*mut u8` so that the provenance can be tracked. Furthermore, the tests for the bump allocator were missing so I added them.

## Pre-Review Checklist for the PR Author

* [x] Add sensible notes for the reviewer
* [x] PR title is short, expressive and meaningful
* [x] Consider switching the PR to a draft (`Convert to draft`)
    * as draft PR, the CI will be skipped for pushes
* [x] Relevant issues are linked in the [References](#references) section
* [x] Every source code file has a copyright header with `SPDX-License-Identifier: Apache-2.0 OR MIT`
* [x] Branch follows the naming format (`iox2-123-introduce-posix-ipc-example`)
* [x] Commits messages are according to this [guideline][commit-guidelines]
    * [x] Commit messages have the issue ID (`[#123] Add posix ipc example`)
    * [x] Commit author matches [Eclipse Contributor Agreement][eca](and ECA is signed)
* [x] Tests follow the [best practice for testing][testing]
* [x] Changelog updated [in the unreleased section][changelog] including API breaking changes
* [x] Assign PR to reviewer
* [x] All checks have passed (except `task-list-completed`)

[commit-guidelines]: https://tbaggery.com/2008/04/19/a-note-about-git-commit-messages.html
[eca]: http://www.eclipse.org/legal/ECA.php
[testing]: https://github.com/eclipse-iceoryx/iceoryx/blob/master/doc/website/concepts/best-practice-for-testing.md
[changelog]: https://github.com/eclipse-iceoryx/iceoryx2/blob/main/doc/release-notes/iceoryx2-unreleased.md

## Checklist for the PR Reviewer

* [x] Commits are properly organized and messages are according to the guideline
* [x] Unit tests have been written for new behavior
* [x] Public API is documented
* [x] PR title describes the changes

## Post-review Checklist for the PR Author

* [x] All open points are addressed and tracked via issues

## References

Closes #992 
Closes #991

### CODE REVIEW

File: iceoryx2-bb/elementary/src/bump_allocator.rs [hunk 1]
```diff
@@ -41,12 +41,15 @@ impl BaseAllocator for BumpAllocator {
 
         unsafe {
             Ok(core::ptr::NonNull::new_unchecked(
-                core::slice::from_raw_parts_mut(mem as *mut u8, layout.size()),
+                core::slice::from_raw_parts_mut(
+                    self.start.add(mem - self.start as usize),
```
[the remark this answers is not in the document]
Comment (elfenpiff) [reply iceoryx2-bb/elementary/src/bump_allocator.rs:45]: This would destroy the pointer provenance

File: iceoryx2-bb/elementary/src/bump_allocator.rs [hunk 2]
```diff
@@ -17,16 +17,16 @@ use iceoryx2_pal_concurrency_sync::iox_atomic::IoxAtomicUsize;
 
 /// A minimalistic [`BumpAllocator`].
 pub struct BumpAllocator {
-    start: usize,
+    start: *mut u8,
     pos: IoxAtomicUsize,
```
Comment (elBoberido) [inline iceoryx2-bb/elementary/src/bump_allocator.rs:21]: Not for this PR, but does this need to be atomic at all?

**Review by elBoberido — DISMISSED** [review]

File: iceoryx2-bb/elementary/src/bump_allocator.rs (hunk 2 above)
Comment (elfenpiff) [reply iceoryx2-bb/elementary/src/bump_allocator.rs:21]: Nope, but it is much nicer to handle than `UnsafeCell<usize>`

Comment (elBoberido) [reply iceoryx2-bb/elementary/src/bump_allocator.rs:21]: Maybe a `good first issue`?

Oh, and can `start` ever be a null pointer? Potentially this could also become a `NonNull` ... also not in this PR but a `good first issue`?
